### ISSUE TITLE
首先恭喜您的论文被接受，由于github上没有论文地址，请问您提供下文章的title嘛？如果有链接那就更感谢了！！！

### ISSUE THREAD

**Issue by qiang333** [Xyporz/CISSL-GANs#1]

**Comment by Xyporz** [comment]
谢谢！文章标题：Fundus Image-label Pairs Synthesis and Retinopathy Screening via GANs with Class-imbalanced Semi-supervised Learning，您现在可以在链接 https://ieeexplore.ieee.org/document/10087263 中获取到文章。
